# -*- coding: utf-8 -*-
"""
Created on Tue May 20 15:49:19 2025

@author: mhmtn
"""
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import string 
from collections import Counter

# %% data
positive_sentences = [  # 100 positive sentences
    "This movie was absolutely amazing!",
    "I really enjoyed the food at that restaurant.",
    "The new update made the app so much better.",
    "She did a fantastic job on her presentation.",
    "The design of this website is very clean and modern.",
    "I love how easy it is to use this software.",
    "That was such a thoughtful gift.",
    "His performance was incredibly inspiring.",
    "I’m impressed by how smoothly everything went.",
    "The atmosphere here is really relaxing.",
    "This book kept me hooked from start to finish.",
    "Your explanation made things so much clearer.",
    "The colors in this painting are beautiful.",
    "What a lovely surprise that was!",
    "I think you handled that situation really well.",
    "The service was quick and friendly.",
    "This game is so much fun to play!",
    "The view from this place is breathtaking.",
    "I love the creativity in this project.",
    "Everything turned out even better than expected.",
    "That’s a really clever idea!",
    "I appreciate the attention to detail here.",
    "This place has such a positive vibe.",
    "The music really sets the perfect mood.",
    "You’ve made a lot of progress — well done!",
    "I’m so glad I bought this product.",
    "The packaging was neat and professional.",
    "This documentary was both informative and engaging.",
    "You explained that concept so well.",
    "I love how responsive the support team was.",
    "The user interface is very intuitive.",
    "The experience was worth every penny.",
    "Such a heartwarming story!",
    "This laptop works like a charm.",
    "You look great in that outfit!",
    "The timing of the event was perfect.",
    "That recipe turned out delicious!",
    "This travel guide was super helpful.",
    "Your photography skills are impressive.",
    "The decorations really brighten up the room.",
    "I admire how dedicated you are.",
    "This playlist has the perfect vibe.",
    "The presentation was clear and engaging.",
    "These shoes are incredibly comfortable.",
    "I laughed so much during the show!",
    "This app saves me so much time.",
    "You always bring a fresh perspective.",
    "The character development was brilliant.",
    "I feel very welcomed here.",
    "Your hard work truly paid off.",
    "The coffee here is excellent.",
    "This phone has amazing battery life.",
    "Everything was neatly organized.",
    "That scene gave me goosebumps!",
    "This course is really well structured.",
    "I learned so much from that workshop.",
    "The lighting is just right in this photo.",
    "The idea behind this project is genius.",
    "Such a great turnout for the event!",
    "You did a great job with the setup.",
    "I love how thoughtful the design is.",
    "The staff was super helpful.",
    "That solution was very innovative.",
    "These colors really complement each other.",
    "This tutorial made it so easy to understand.",
    "I had a great time at the party.",
    "The engine runs very smoothly.",
    "This watch feels so premium.",
    "Your feedback was really constructive.",
    "Such a relaxing place to unwind.",
    "The editing in this video is top-notch.",
    "The quality exceeded my expectations.",
    "This place has great energy.",
    "That meal hit the spot!",
    "I love the simplicity of this setup.",
    "Your ideas are always so original.",
    "You’ve got a real talent for writing.",
    "Everything looks so clean and tidy.",
    "This jacket is both stylish and warm.",
    "That was a really moving speech.",
    "This game has such rich storytelling.",
    "The response was super fast.",
    "This makes my work much easier.",
    "The app’s interface is really sleek.",
    "This class was very interactive and fun.",
    "It’s refreshing to see such honesty.",
    "The layout is very user-friendly.",
    "This keyboard feels great to type on.",
    "That was the perfect gift.",
    "The team really pulled together on this one.",
    "That video had excellent pacing.",
    "The flavors in this dish are amazing.",
    "You’re great at solving problems.",
    "Everything was delivered on time.",
    "The story had a very satisfying ending.",
    "That was the smoothest ride I’ve ever had.",
    "This environment helps me focus well.",
    "You handled that like a pro.",
    "The smell of this candle is so calming.",
    "That suggestion worked perfectly.",
    "You always know just what to say.",
    "This pen writes so smoothly.",
    "Such a peaceful and scenic route.",
    "This tool is a total game-changer.",
    "I absolutely loved the performance tonight.",
    "Everything about this trip was wonderful.",
    "She really knows how to make people smile.",
    "This cake tastes heavenly!",
    "I feel so refreshed after that workout.",
    "The staff here are always cheerful and helpful.",
    "That was a truly unforgettable moment.",
    "The feedback I received was very encouraging.",
    "This new feature is exactly what I needed.",
    "It’s always a pleasure working with you.",
    "This event was a huge success.",
    "You always know how to lift the mood.",
    "I admire your dedication and enthusiasm.",
    "That was such a generous offer.",
    "This solution works flawlessly.",
    "You made my day with that comment.",
    "The project exceeded all expectations.",
    "It’s so satisfying to see the results.",
    "Everything turned out better than I imagined.",
    "I can't wait to come back here again.",
    "Your support means the world to me.",
    "The design choices are top-notch.",
    "I had such a good time today.",
    "Your attention to detail is impressive.",
    "That was the perfect ending.",
    "I appreciate how well you handled that.",
    "That compliment really boosted my confidence.",
    "This feels like a fresh start.",
    "Everything came together perfectly.",
    "The team spirit here is inspiring.",
    "Your work ethic is admirable.",
    "Such a peaceful and cozy space.",
    "The menu offers great variety.",
    "This app has everything I need.",
    "You nailed it!",
    "That was just the right touch.",
    "You’ve got a great eye for design.",
    "The sound quality is crystal clear.",
    "You made a real difference today.",
    "This story really touched me.",
    "Your writing is so engaging.",
    "The whole experience was delightful.",
    "The decorations set the mood perfectly.",
    "Your passion really shines through.",
    "Such a brilliant concept!",
    "This song gives me chills every time.",
    "You’ve come a long way — congrats!",
    "The community here is so welcoming.",
    "That was an incredibly thoughtful gesture.",
    "The textures in this dish are perfect.",
    "You’ve made impressive progress.",
    "The results are even better than I hoped.",
    "The pace of the course is just right.",
    "This is one of the best decisions I’ve made.",
    "You always go above and beyond.",
    "It’s great to see you thriving.",
    "The balance of flavors is just right.",
    "I love your sense of style.",
    "This view is absolutely stunning.",
    "You’ve created something truly special.",
    "This chair is the definition of comfort.",
    "You inspire me with your creativity.",
    "That was a beautifully executed plan.",
    "The vibe here is so positive.",
    "The scent is subtle but lovely.",
    "I’ve never felt so relaxed.",
    "That message was very uplifting.",
    "Your creativity really shines through.",
    "This is one of my favorite places.",
    "That move was genius.",
    "The lighting adds so much to the mood.",
    "I really value your insight.",
    "You handled that challenge gracefully.",
    "This book opened my mind.",
    "This team works so well together.",
    "I’m in awe of your skills.",
    "You made everything so easy.",
    "It’s such a pleasure to be part of this.",
    "I admire your positive attitude.",
    "This fabric feels luxurious.",
    "I’m so happy with this result.",
    "The layout is very pleasing.",
    "Your sense of humor is fantastic.",
    "The transitions were so smooth.",
    "That made me smile.",
    "The tool is incredibly user-friendly.",
    "You managed that like a pro.",
    "The flavors blend together beautifully.",
    "You’ve got a real gift for storytelling.",
    "I love how this turned out.",
    "That color choice is perfect.",
    "This playlist really fits my mood.",
    "Everything works just as it should.",
    "You brought this idea to life brilliantly.",
    "The presentation was captivating.",
    "This feedback is so encouraging.",
    "I feel energized after using this.",
    "That advice was exactly what I needed.",
    "This setup is very efficient.",
    "I appreciate your transparency.",
    "The visuals are absolutely stunning.",
    "You brought such great energy.",
    "It’s been a fantastic journey.",
    "That performance gave me goosebumps.",
    "I learned something valuable today.",
    "This is so well thought out.",
    "You’ve mastered this craft.",
    "You made such a smart decision.",
    "This feels very intuitive.",
    "You captured the moment perfectly.",
    "This app really simplified my workflow.",
    "You always know how to motivate me.",
    "I’m grateful for your perspective.",
    "You turned the situation around brilliantly.",
    "That’s an incredible achievement.",
    "I’m proud of what we accomplished.",
    "That tasted absolutely delicious.",
    "This is exactly what I was looking for.",
    "That was such a creative solution.",
    "This fragrance is divine.",
    "You turned a challenge into a triumph.",
    "I feel inspired after watching that.",
    "That explanation was very clear.",
    "Everything looks so professional.",
    "I’m blown away by the quality.",
    "You’ve set a great example.",
    "You always bring such clarity.",
    "The design is sleek and modern.",
    "You have a real knack for this.",
    "The environment here is very uplifting.",
    "That really warmed my heart.",
    "Your dedication shows in the results.",
    "I’m thrilled with the outcome.",
    "The feedback has been overwhelmingly positive.",
    "You’ve gone above expectations.",
    "This is a real breakthrough.",
    "You really outdid yourself.",
    "This exceeded all my hopes.",
    "Your words were so comforting.",
    "I’m genuinely impressed.",
    "Everything just clicks perfectly.",
    "The message was powerful and clear.",
    "Your perspective is refreshing.",
    "That felt so genuine and kind.",
    "The tone was spot on.",
    "This solution is elegant and simple.",
    "You’ve built something amazing here.",
    "The implementation was flawless.",
    "I’m so glad I experienced this.",
    "That event was incredibly memorable.",
    "You’ve made a lasting impression.",
    "Your kindness never goes unnoticed.",
    "You brought light to a dull day.",
    "This product is worth every penny.",
    "You really listened and delivered.",
    "The storytelling was so compelling.",
    "You always bring value to the table.",
    "That result speaks for itself.",
    "You handled feedback maturely.",
    "This feels very polished.",
    "The pacing kept me engaged.",
    "You have great instincts.",
    "I appreciate your calm approach.",
    "This is such a rewarding experience.",
    "You brought so much to the discussion.",
    "You’re a natural at this.",
    "This is a masterpiece.",
    "You’ve got such a unique style.",
    "Everything went so smoothly.",
    "That joke really landed!",
    "Your timing was perfect.",
    "This has become a favorite of mine.",
    "You’ve got a great way with words.",
    "You added a magical touch.",
    "That feature works like a dream.",
    "You really understand the audience.",
    "This exceeded expectations in every way.",
    "That compliment meant a lot to me.",
    "You’ve created a beautiful atmosphere.",
    "This helped me see things differently.",
    "The support team was outstanding.",
    "That idea deserves recognition.",
    "Everything just came together so well.",
    "This space is so inviting.",
    "The camera clarity is amazing.",
    "This keyboard is so responsive.",
    "I’m truly impressed by your growth.",
    "The planning was impeccable.",
    "This photo tells a powerful story.",
    "You made a great impression.",
    "That interaction was very uplifting.",
    "The aesthetics are stunning.",
    "You always show up with a smile.",
    "I left feeling encouraged.",
    "This truly made a difference."
]



negative_sentences = [  # 100 negative sentences
    "This movie didn’t live up to the hype.",
    "The food was pretty bland, unfortunately.",
    "The app keeps freezing on my phone.",
    "Her explanation just made it more confusing.",
    "The website takes forever to load.",
    "I had higher expectations for this product.",
    "The update made things worse, not better.",
    "This event felt poorly organized.",
    "The book was too slow for my taste.",
    "The lighting in the room was awful.",
    "I wasn’t impressed by the service.",
    "The instructions weren’t clear at all.",
    "This phone dies too quickly.",
    "The sound quality was disappointing.",
    "I found the conversation quite boring.",
    "The app layout is really confusing.",
    "This software keeps crashing.",
    "It took too long to get a response.",
    "The music was way too loud.",
    "The game felt repetitive after a while.",
    "The experience just felt very underwhelming.",
    "This chair is super uncomfortable.",
    "The delivery was delayed without notice.",
    "That joke didn’t land at all.",
    "The customer service was unhelpful.",
    "The interface looks outdated.",
    "That class was really hard to follow.",
    "I couldn’t get into the storyline.",
    "This design feels a bit sloppy.",
    "The keyboard is way too stiff.",
    "I expected better build quality.",
    "This dish was too salty for me.",
    "The pacing of the movie was off.",
    "This didn’t taste fresh at all.",
    "The screen flickers sometimes.",
    "I regret buying this product.",
    "The setup process was a nightmare.",
    "That speech lacked energy.",
    "The color looked different in person.",
    "It was hard to stay awake through the lecture.",
    "This tool broke after a few uses.",
    "The idea is good, but the execution is poor.",
    "The experience wasn’t worth the price.",
    "That presentation was all over the place.",
    "This file won’t open no matter what I do.",
    "The atmosphere felt tense and awkward.",
    "The app is full of annoying ads.",
    "I couldn’t connect to the Wi-Fi.",
    "The support team took days to reply.",
    "This fabric feels really cheap.",
    "I felt ignored the entire time.",
    "The smell of the product is unpleasant.",
    "This place needs better maintenance.",
    "The plot was too predictable.",
    "The room was freezing cold.",
    "That explanation was too vague.",
    "The controller buttons are too stiff.",
    "The camera quality is grainy.",
    "The staff seemed disinterested.",
    "I don’t like the new interface at all.",
    "This mattress is way too firm.",
    "The visuals weren’t very impressive.",
    "The font is too small to read.",
    "The walls are too thin, I hear everything.",
    "That was a very awkward moment.",
    "It just doesn’t work like it should.",
    "This feels like a downgrade.",
    "That message came off as rude.",
    "It was hard to find parking.",
    "This machine makes too much noise.",
    "I felt rushed during the appointment.",
    "The description was misleading.",
    "That wasn’t a great first impression.",
    "The taste didn’t match the smell.",
    "The pages fell out of the book.",
    "The fabric shrunk after one wash.",
    "It overheats quickly.",
    "I didn’t feel welcome at all.",
    "The battery drains so fast.",
    "The update deleted my settings.",
    "This is missing a lot of basic features.",
    "It feels cheaply made.",
    "The video buffering was unbearable.",
    "The remote stopped working.",
    "This place doesn’t match the photos.",
    "I had trouble understanding the accent.",
    "The volume level keeps fluctuating.",
    "The text was full of typos.",
    "The app kept logging me out.",
    "I wish they had more options.",
    "The website crashed repeatedly.",
    "I got a headache from the noise.",
    "There were too many interruptions.",
    "The color faded really quickly.",
    "The navigation menu is buggy.",
    "That felt like a waste of time.",
    "The content was very shallow.",
    "I wouldn’t recommend this to anyone.",
    "It lacks the features I needed.",
    "The heat doesn’t distribute evenly.",
    "The fan is way too loud.",
    "This cable stopped working after a week.",
    "I didn’t get what I paid for.",
    "The message was not clear at all.",
    "This setup is far too complicated.",
    "I was really disappointed with the service.",
    "This just isn't working the way it should.",
    "The quality is far below expectations.",
    "It took forever to load.",
    "I didn’t enjoy the experience at all.",
    "The instructions were very confusing.",
    "Nothing about this felt right.",
    "The sound was muffled and unclear.",
    "I regret purchasing this.",
    "That comment was really unnecessary.",
    "It was more frustrating than helpful.",
    "I felt ignored and unappreciated.",
    "The interface is very clunky.",
    "This version is worse than the last one.",
    "Everything felt rushed and unorganized.",
    "The visuals were dull and uninspired.",
    "This made things even more complicated.",
    "It broke after a single use.",
    "Customer service was unresponsive.",
    "It’s not worth the price.",
    "That decision didn’t make any sense.",
    "It failed to deliver on its promises.",
    "I wouldn’t recommend this to anyone.",
    "The app keeps crashing.",
    "The atmosphere felt tense and cold.",
    "There’s no improvement at all.",
    "It lacked any real value.",
    "The design is outdated and unattractive.",
    "I encountered constant bugs.",
    "It left a bad taste in my mouth.",
    "It didn’t meet even the basic requirements.",
    "This was a complete waste of time.",
    "The support team didn’t help at all.",
    "Everything felt disorganized.",
    "It made things worse, not better.",
    "I found it hard to follow.",
    "That tone came off as rude.",
    "I didn’t feel safe there.",
    "The content felt shallow and repetitive.",
    "It wasn’t worth the effort.",
    "That feature is completely broken.",
    "The font is hard to read.",
    "It made me feel worse, not better.",
    "There were too many errors.",
    "I didn’t feel heard or understood.",
    "It’s missing essential features.",
    "I’m extremely dissatisfied.",
    "This seems poorly tested.",
    "The temperature was way off.",
    "It’s uncomfortable to use.",
    "The performance was underwhelming.",
    "I couldn’t find any useful information.",
    "The visuals looked unprofessional.",
    "It caused more confusion than clarity.",
    "I wouldn’t go back.",
    "It’s incredibly laggy.",
    "The explanation wasn’t clear.",
    "That was not what I expected.",
    "It’s full of annoying ads.",
    "I felt unwelcome the entire time.",
    "It constantly freezes.",
    "There was a noticeable delay.",
    "The update made it worse.",
    "I didn’t like the tone of that email.",
    "The app drains the battery fast.",
    "That joke was inappropriate.",
    "It left me feeling annoyed.",
    "There’s no consistency at all.",
    "This experience was exhausting.",
    "I feel like my time was wasted.",
    "The options are too limited.",
    "The support felt robotic.",
    "I felt misled by the description.",
    "The site layout is chaotic.",
    "I can’t trust this brand anymore.",
    "The attitude was unprofessional.",
    "It looks cheap and flimsy.",
    "I wouldn’t wish this on anyone.",
    "Everything about this felt fake.",
    "It’s hard to navigate.",
    "That behavior was unacceptable.",
    "The camera quality is terrible.",
    "Nothing worked as intended.",
    "The entire process was frustrating.",
    "I felt completely let down.",
    "The menu was confusing.",
    "That feature doesn’t even work.",
    "There was no follow-up.",
    "It’s filled with typos.",
    "I had high hopes, but I was let down.",
    "I feel ripped off.",
    "The battery life is awful.",
    "This doesn't even look finished.",
    "The software is too buggy to use.",
    "It was way too noisy.",
    "It took too much effort to get started.",
    "I had a hard time understanding it.",
    "This just feels cheap.",
    "The presentation was messy.",
    "Nothing about this impressed me.",
    "The tone came off as sarcastic.",
    "I couldn’t complete the task.",
    "This caused more harm than good.",
    "It didn’t work on my device.",
    "Everything felt forced.",
    "The app crashed repeatedly.",
    "It feels like a scam.",
    "I expected more professionalism.",
    "It didn’t solve the issue.",
    "I was left waiting too long.",
    "It doesn’t match the description.",
    "This felt like a step backward.",
    "That was really uncomfortable to watch.",
    "I couldn’t make sense of the layout.",
    "It’s hard to believe someone approved this.",
    "That was just plain rude.",
    "The voice quality is terrible.",
    "This interface is outdated.",
    "I felt insulted.",
    "Nothing works as it should.",
    "The text is too small to read.",
    "That made the situation worse.",
    "The explanation was too vague.",
    "I didn’t get the help I needed.",
    "The visuals are poorly designed.",
    "That was a letdown.",
    "There’s no logic in this design.",
    "I found it to be very boring.",
    "It lacked any excitement.",
    "It’s visually unappealing.",
    "I’m disappointed with the results.",
    "The tone was very condescending.",
    "This is incredibly slow.",
    "It’s just too complicated.",
    "I don’t feel confident using it.",
    "It made me feel anxious.",
    "This is hard to look at.",
    "It’s riddled with flaws.",
    "I couldn’t get it to work.",
    "This made things more difficult.",
    "That was an awkward experience.",
    "The service felt impersonal.",
    "It gave me incorrect results.",
    "I didn’t find it helpful at all.",
    "This version is very unstable.",
    "That meeting was a waste of time.",
    "I felt like nobody cared.",
    "It’s incredibly unintuitive.",
    "I was expecting something better.",
    "The event was poorly managed.",
    "The performance lacked energy.",
    "It felt like a bad copy.",
    "This is way too slow to use.",
    "There was nothing interesting.",
    "It’s filled with unnecessary steps.",
    "I found the message offensive.",
    "There’s zero creativity here.",
    "That made things more confusing.",
    "The timing was all wrong.",
    "I don’t think I’ll use this again.",
    "It’s completely unreliable.",
    "Everything feels broken.",
    "This should have been tested more.",
    "It made no sense at all.",
    "The response time was unacceptable.",
    "It’s just a mess.",
    "I wish I could get a refund.",
    "This seems half-finished.",
    "The formatting is all over the place.",
    "It felt like no effort was put in.",
    "It’s cluttered and messy.",
    "I felt like giving up.",
    "It gave me a headache.",
    "That was hard to sit through.",
    "This isn’t functional.",
    "It didn’t fit properly.",
    "I lost interest quickly.",
    "It was too loud and chaotic.",
    "I couldn’t relate to any of it.",
    "This lacks structure.",
    "The whole thing was pointless.",
    "That really irritated me.",
    "I don’t feel comfortable using this.",
    "It feels rushed and incomplete.",
    "There’s nothing new here.",
    "I was very underwhelmed.",
    "It doesn’t work offline.",
    "I felt like a burden asking for help.",
    "That left a really bad impression.",
    "It’s just not enjoyable.",
    "It feels cold and lifeless.",
    "I didn’t connect with the material.",
    "There were so many problems.",
    "This is overly complicated.",
    "I don’t see any improvement.",
    "It made me feel worse.",
    "I wouldn’t try this again.",
    "It’s just not worth it.",
    "I didn’t see any results.",
    "The screen kept freezing.",
    "It caused more stress than it solved.",
    "It was very underwhelming.",
    "This makes no sense.",
    "That felt like a waste of energy.",
    "The experience was terrible overall.",
    "This ruined my mood.",
    "The response was disappointing.",
    "I don’t feel satisfied.",
    "It completely failed to deliver.",
    "There’s no attention to detail.",
    "That tone was offensive.",
    "I felt ignored the entire time.",
    "The whole experience was a mess.",
    "I ended up uninstalling it.",
    "That did not go well.",
    "There’s too much going on.",
    "It made me uncomfortable.",
    "This left a negative impression.",
    "It felt fake and forced.",
    "I had high hopes but was let down."
]



def preproces(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text

data = positive_sentences + negative_sentences
labels = [1] * len(positive_sentences) + [0] * len(negative_sentences)
data = [preproces(sentence) for sentence in data]

vocabs = " ".join(data).split()
word_counts = Counter(vocabs)
vocab = {word: idx + 1 for idx, (word, _) in enumerate(word_counts.items())}
vocab["<PAD>"] = 0
max_len = 15

def sentence_to_tensor(sentence, vocab, max_len=15):
    tokens = sentence.split()
    indices = [vocab.get(word, 0) for word in tokens]
    indices = indices[:max_len]
    indices += [0] * (max_len - len(indices))
    return torch.tensor(indices)

x = torch.stack([sentence_to_tensor(sentence, vocab, max_len) for sentence in data])
y = torch.tensor(labels)

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, train_size=0.7)

class Transformerclass(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_heads, num_layers, hidden_dim, num_classes):
        super(Transformerclass, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.positional_encoding = nn.Parameter(torch.randn(1, max_len, embed_dim))
        self.transformer = nn.Transformer(
            d_model=embed_dim,
            nhead=num_heads,
            num_encoder_layers=num_layers,
            dim_feedforward=hidden_dim
        )
        self.fc = nn.Linear(embed_dim * max_len, hidden_dim)
        self.out = nn.Linear(hidden_dim, num_classes)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        embedded = self.embedding(x) + self.positional_encoding
        embedded = embedded.transpose(0, 1)
        output = self.transformer(embedded, embedded)
        output = output.transpose(0, 1)
        output = output.contiguous().view(output.size(0), -1)
        output = torch.relu(self.fc(output))
        output = self.out(output)
        output = self.sigmoid(output)
        return output

vocab_size = len(vocab)
embed_dim = 32
num_heads = 4
num_layers = 4
hidden_dim = 64
num_classes = 1
num_epochs = 30

model = Transformerclass(vocab_size, embed_dim, num_heads, num_layers, hidden_dim, num_classes)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.0005)
#%% test

model.train()
for epoch in range(num_epochs):
    optimizer.zero_grad()
    output = model(x_train.long()).squeeze()
    loss = criterion(output, y_train.float())
    loss.backward()
    optimizer.step()
    print(f"epoch:{epoch+1}/{num_epochs}, loss:{loss.item():.4f}")
model.eval()
with torch.no_grad():
    y_pred=model(x_test.long()).squeeze()
    y_pred=(y_pred>0.5).float()
    y_pred_train=model(x_train.long()).squeeze()
    y_pred_train=(y_pred_train>0.5).float()
    
accuracy=accuracy_score(y_test, y_pred)
print(f"accuracy:{accuracy}")
accuracy_train=accuracy_score(y_train, y_pred_train)
print(f"train accuracy:{accuracy_train}")
























